#!/bin/bash
#Written by seeger54367
#Takes a resume written in yaml and produces a final pdf file
ymlResume="resume.yml"
mdResume="resume.md"
pdfResume="finished_resume.pdf"

addEmployment () {
  echo -e "## Employment\n" >> "${mdResume}"
  yq e '.Employment[] | "## "+ .Position +" - "+ .Company +" "+ .Start +"-"+ .End +"<CR>"+ .Tasks' "${ymlResume}" >> "${mdResume}"
}

addProjects() {
  echo -e "## Projects\n" >> "${mdResume}"
  yq e '.Projects[] | "## "+ .Name + "<CR>" + .Summary' "${ymlResume}" >> "${mdResume}"
}

main () {
  [[ -e "${mdResume}" ]] && truncate -s0 "${mdResume}"
  yq e '"# " + .Name +"<CR>"' "${ymlResume}" >> "${mdResume}"
  addEmployment
  addProjects
  #Trying to find a replacement for sed
  sed -E "s/<CR>/\n\n/" -i.bak "${mdResume}"
  pandoc -V geometry:margin=0.75in -o "${pdfResume}" -t latex "${mdResume}"
  exit 0
}

[[ -n "${1}" ]] && ymlResume="${1}"
([[ -e "${ymlResume}" ]] && main) || (echo "Designated file doesn't exist" && exit 32)
