#!/bin/bash

[[ -z $WORKOUTLOG ]] && echo "WORKOUTLOG variable not set"
[[ -z $WEIGHTFILE ]] && echo "WEIGHTFILE variable not set"
[[ -z $CHALLENGEFILE ]] && echo "CHALLENGEFILE variable not set"
goal=100
currDay="$(date -u +"%w")"
currDate="$(date -u +%Y%m%d)"
progressLine="$(tail -n 1 "${CHALLENGEFILE}")"
[[ ${progressLine##* } = "${currDate}" ]] && repsMade="${progressLine%% *}" || repsMade=0

# ------------------------- complete context -------------------------

declare -a COMMANDS=(addworkout addexercise addweight getChallengeStatus updateChallenge)

if [[ -n $COMP_LINE ]]; then
    for c in "${COMMANDS[@]}"; do
        [[ ${c:0:${#2}} = "${2,,}" ]] && echo "$c"
    done
    exit
fi

# -------------------------- end completion --------------------------


addworkout(){
  test -z "${1}" && echo "Please enter a workout Type (A or B)" && exit
  workoutType="${1}"
  # printf "\n- date: $(date)\n  - type: %s\n  - Exercises:\n    -\n" "${workoutType}" >> "${WORKOUTLOG}" 
  if [[ ${workoutType} == "A" ]]
  then
    printf "\n- date: $(date)
  - type: %s
  - Warmup:
    - 25 walking jacks
    - front punch
    - high punch
    - front kick
    - 10 knee knuckle pushups
    - in-to-out cresant kick
    - out-to-in cresant kick
  - Exercises:
    - x decline knuckle pushups 3x sets
    - x bench dumbbell rows each arm @20lbs. 3x sets
    - x inverted bodyweight rows on doorframe. 3x sets
    - x lunges
    - plank1 x'xx\"xx
    - plank2 x'xx\"xx
    - plank3 x'xx\"xx
" "${workoutType}" >> "${WORKOUTLOG}" 
  elif [[ ${workoutType} == "B" ]]
  then
    printf "\n- date: $(date)\n  - type: %s
  - Warmup:
    - 26 walking jacks
    - front punch
    - high punch
    - front kick
    - 10 knee knuckle pushups
    - in-to-out cresant kick
    - out-to-in cresant kick
  - Exercises:
    - x regular knuckle pushups 3x sets
    - x bench dumbbell rows each arm @20lbs. 3x sets
    - x inverted bodyweight rows on doorframe. 3x sets
    - x squats
    - plank1 x'xx\"xx
    - plank2 x'xx\"xx
    - plank3 x'xx\"xx" "${workoutType}" >> "${WORKOUTLOG}" 
    else
      echo "Please enter A or B" && exit
  fi
  exec vim "${WORKOUTLOG}"
}


addexercise(){
  printf "    -\n" >> "${WORKOUTLOG}"
  exec vim "${WORKOUTLOG}"
}

addweight(){
  curDate="$(date)"
  printf "\n- date: %s\n  - weight: " "${curDate}" >> "${WEIGHTFILE}"
  exec vim "${WEIGHTFILE}"
}

setChallengeVars(){
  [[ $currDay = 1 || $currDay = 4 ]] && challenge="pushups"
  [[ $currDay = 2 || $currDay = 5 ]] && challenge="situps"
  [[ $currDay = 3 || $currDay = 6 ]] && challenge="squats"
  [[ $currDay = 0 || $currDay = 7 ]] && echo "No Challenge today. Have a relaxing day!" && exit
  [[ ${progressLine##* } = "${currDate}" ]] || (echo "0 ${challenge} ${currDate}" >> "${CHALLENGEFILE}" && echo "Added challenge entry")
  progressLine="$(tail -n 1 "${CHALLENGEFILE}")"
}

getChallengeStatus(){
  setChallengeVars
  echo "Today's challenge is ${goal} ${challenge}"
  numberLeft="$(echo "scale=2; ${goal} - ${repsMade}" | bc)"
  ([[ ${progressLine##* } = "${currDate}" ]] && echo "${repsMade} completed so far. ${numberLeft} to go.") || echo "No reps completed so far. ${goal} reps to go."
}

updateChallenge() {
  setChallengeVars
  [[ ${progressLine##* } = "${currDate}" ]] && read -rp "How many reps do you want to add? " addedReps && newReps="$(echo "scale=2; ${addedReps} + ${repsMade}" | bc)" 
  sed -i "s/${progressLine}/${newReps} ${challenge} ${currDate}/" "${CHALLENGEFILE}"
  # printf "%s\n%s %s %s\n" "$(sed \$d ${CHALLENGEFILE})" "${newReps}" "${challenge}" "${currDate}" > "${CHALLENGEFILE}"
}

main(){
  [[ -z $1 ]] && echo "Please enter a subcommand." && exit
  "$@"
}

main "$@"
